name = "hummingbird-camera"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hummingbird-captures"

[[d1_databases]]
binding = "DB"
database_name = "hummingbird-heartbeat"
database_id = "6b740056-e015-4765-b964-f49eac176e15"

[vars]
MAX_FILES = 19500

[triggers]
crons = ["*/15 * * * *"]
